"""Generate lua/apidocs/linguist_languages.lua from GitHub Linguist.

Usage: python3 scripts/gen_linguist_languages.py <path to languages.yml>
Source: https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml
Linguist is MIT licensed (Copyright (c) 2017 GitHub, Inc.); the generated file
keeps that notice. Every entry is kept, obscure ones included: the table is
what lets a documentation source name its language.
"""
import sys

import yaml


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


data = yaml.safe_load(open(sys.argv[1]))
out = [
    "-- GENERATED by scripts/gen_linguist_languages.py from GitHub Linguist's",
    "-- languages.yml. Do not edit by hand; re-run the script.",
    "--",
    "-- Linguist: Copyright (c) 2017 GitHub, Inc., MIT License.",
    "--",
    "-- name -> { type = programming|markup|data|prose, aliases = { ... } }",
    "return {",
]
for name in sorted(data, key=str.lower):
    entry = data[name]
    aliases = ", ".join(lua_string(a) for a in entry.get("aliases") or [])
    out.append(f"  [{lua_string(name)}] = {{ type = {lua_string(entry['type'])}, aliases = {{ {aliases} }} }},")
out.append("}")
open("lua/apidocs/linguist_languages.lua", "w").write("\n".join(out) + "\n")
print(len(data), "languages")
